# This file contains the list of tests that should be included and excluded.
#
# To provide a better UX, the 'cliFocus' defined on each element from the
#  "include" is expanded to the specific defined 'focus'. This way we can map
#  which regex should be used on ginkgo --focus to an element from the "focus"
#  list.
#
# Further down is a list of tests that can be excluded because they are ignored
# by our constraints defined in the ginkgo tests. There is a justification, in
# form of a comment, explaining why each test is excluded.
#
# More info: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
---
focus:
- "f09-datapath-misc-2-1"
- "f09-datapath-misc-2-2"
include:
  ###
  # K8sDatapathConfig Check BPF masquerading with ip-masq-agent DirectRouting
  # K8sDatapathConfig Check BPF masquerading with ip-masq-agent VXLAN
  # K8sDatapathConfig High-scale IPcache Test ingress policy enforcement with GENEVE and endpoint routes
  # K8sDatapathConfig High-scale IPcache Test ingress policy enforcement with VXLAN and no endpoint routes
  # K8sDatapathConfig Iptables Skip conntrack for pod traffic
  # K8sDatapathConfig IPv4Only Check connectivity with IPv6 disabled
  # K8sDatapathConfig IPv6 masquerading across K8s nodes, skipped due to native routing CIDR
  # K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing with bpf_host
  - focus: "f09-datapath-misc-2-1"
    cliFocus: "K8sDatapathConfig Transparent"

  ###
  # K8sDatapathConfig Check BPF masquerading with ip-masq-agent DirectRouting
  # K8sDatapathConfig Check BPF masquerading with ip-masq-agent VXLAN
  # K8sDatapathConfig High-scale IPcache Test ingress policy enforcement with GENEVE and endpoint routes
  # K8sDatapathConfig High-scale IPcache Test ingress policy enforcement with VXLAN and no endpoint routes
  # K8sDatapathConfig Iptables Skip conntrack for pod traffic
  # K8sDatapathConfig IPv4Only Check connectivity with IPv6 disabled
  # K8sDatapathConfig IPv6 masquerading across K8s nodes, skipped due to native routing CIDR
  # K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing with bpf_host
  - focus: "f09-datapath-misc-2-2"
    cliFocus: "K8sDatapathConfig Transparent"

exclude:
  # The bandwidth test is disabled and hubble tests are not meant
  # to run on net-next.
  - k8s-version: "1.27"
    focus: "f10-agent-hubble-bandwidth"

  # Cilium "v1.13" is not supported in K8s "1.27". Skipping upgrade/downgrade tests.
  - k8s-version: "1.27"
    focus: "f19-update"

  # These tests are meant to run with kube-proxy which is not available
  # with net-next
  - k8s-version: "1.27"
    focus: "f16-datapath-service-ew-2"

  # These tests are meant to run with kube-proxy which is not available
  # with net-next
  - k8s-version: "1.27"
    focus: "f17-datapath-service-ew-kube-proxy"

  # These tests require an external node which is only available on 1.27
  # / net-next so there's no point on running them
  - k8s-version: "1.26"
    focus: "f05-agent-policy-multi-node-2"

  # These tests require kernel net-next so there's no point on running them
  - k8s-version: "1.26"
    focus: "f11-datapath-service-ns-tc"

  - k8s-version: "1.26"
    focus: "f12-datapath-service-ns-misc"

  - k8s-version: "1.26"
    focus: "f13-datapath-service-ns-xdp-1"

  - k8s-version: "1.26"
    focus: "f14-datapath-service-ns-xdp-2"

  # These tests require are not intended to run on kernel 5.4, thus we can ignore them
  - k8s-version: "1.25"
    focus: "f01-agent-chaos"

  - k8s-version: "1.25"
    focus: "f03-agent-policy"

  - k8s-version: "1.25"
    focus: "f04-agent-policy-multi-node-1"

  - k8s-version: "1.25"
    focus: "f05-agent-policy-multi-node-2"

  - k8s-version: "1.25"
    focus: "f11-datapath-service-ns-tc"

  - k8s-version: "1.25"
    focus: "f12-datapath-service-ns-misc"

  - k8s-version: "1.25"
    focus: "f13-datapath-service-ns-xdp-1"

  - k8s-version: "1.25"
    focus: "f14-datapath-service-ns-xdp-2"

  - k8s-version: "1.25"
    focus: "f15-datapath-service-ew-1"

  - k8s-version: "1.25"
    focus: "f16-datapath-service-ew-2"

  - k8s-version: "1.25"
    focus: "f17-datapath-service-ew-kube-proxy"

  - k8s-version: "1.25"
    focus: "f18-datapath-bgp-custom-lrp"

  - k8s-version: "1.25"
    focus: "f20-kafka"

  # These tests require an external node which is only available on 1.27
  # / net-next so there's no point on running them
  - k8s-version: "1.24"
    focus: "f05-agent-policy-multi-node-2"

  # These tests require kernel net-next so there's no point on running them
  - k8s-version: "1.24"
    focus: "f11-datapath-service-ns-tc"

  - k8s-version: "1.24"
    focus: "f12-datapath-service-ns-misc"

  - k8s-version: "1.24"
    focus: "f13-datapath-service-ns-xdp-1"

  - k8s-version: "1.24"
    focus: "f14-datapath-service-ns-xdp-2"

  # These tests require an external node which is only available on 1.27
  # / net-next so there's no point on running them
  - k8s-version: "1.23"
    focus: "f05-agent-policy-multi-node-2"

  # These tests require kernel net-next so there's no point on running them
  - k8s-version: "1.23"
    focus: "f11-datapath-service-ns-tc"

  - k8s-version: "1.23"
    focus: "f12-datapath-service-ns-misc"

  - k8s-version: "1.23"
    focus: "f13-datapath-service-ns-xdp-1"

  - k8s-version: "1.23"
    focus: "f14-datapath-service-ns-xdp-2"

  # These tests require an external node which is only available on 1.27
  # / net-next so there's no point on running them
  - k8s-version: "1.22"
    focus: "f05-agent-policy-multi-node-2"

  # These tests require kernel net-next so there's no point on running them
  - k8s-version: "1.22"
    focus: "f11-datapath-service-ns-tc"

  - k8s-version: "1.22"
    focus: "f12-datapath-service-ns-misc"

  - k8s-version: "1.22"
    focus: "f13-datapath-service-ns-xdp-1"

  - k8s-version: "1.22"
    focus: "f14-datapath-service-ns-xdp-2"

  # These tests require an external node which is only available on 1.27
  # / net-next so there's no point on running them
  - k8s-version: "1.21"
    focus: "f05-agent-policy-multi-node-2"

  # These tests require kernel net-next so there's no point on running them
  - k8s-version: "1.21"
    focus: "f11-datapath-service-ns-tc"

  - k8s-version: "1.21"
    focus: "f12-datapath-service-ns-misc"

  - k8s-version: "1.21"
    focus: "f13-datapath-service-ns-xdp-1"

  - k8s-version: "1.21"
    focus: "f14-datapath-service-ns-xdp-2"

  # These tests require an external node which is only available on 1.27
  # / net-next so there's no point on running them
  - k8s-version: "1.20"
    focus: "f05-agent-policy-multi-node-2"

  # These tests require kernel net-next so there's no point on running them
  - k8s-version: "1.20"
    focus: "f11-datapath-service-ns-tc"

  - k8s-version: "1.20"
    focus: "f12-datapath-service-ns-misc"

  - k8s-version: "1.20"
    focus: "f13-datapath-service-ns-xdp-1"

  - k8s-version: "1.20"
    focus: "f14-datapath-service-ns-xdp-2"

  # These tests require an external node which is only available on 1.27
  # / net-next so there's no point on running them
  - k8s-version: "1.19"
    focus: "f05-agent-policy-multi-node-2"

  # These tests are always skipped so there's no point on running
  - k8s-version: "1.19"
    focus: "f11-datapath-service-ns-tc"

  - k8s-version: "1.19"
    focus: "f12-datapath-service-ns-misc"

  - k8s-version: "1.19"
    focus: "f13-datapath-service-ns-xdp-1"

  - k8s-version: "1.19"
    focus: "f14-datapath-service-ns-xdp-2"
