name: Docs-builder Image Build

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - .github/workflows/build-images-docs-builder.yaml
      - Documentation/Dockerfile
      - Documentation/requirements.txt

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-push:
    timeout-minutes: 45
    environment: release-base-images # To get access to AUTO_COMMITTER_*
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master branch to access local actions
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Set environment variables
        uses: ./.github/actions/set-env-variables

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2.4.1

      - name: Checkout source code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up git
        run: |
          git config user.name "Cilium Imagebot"
          git config user.email "noreply@cilium.io"

      - name: Generate image tag for docs-builder
        id: docs-builder-tag
        run: |
          echo tag="$(git ls-tree --full-tree HEAD -- ./Documentation | awk '{ print $3 }')" >> $GITHUB_OUTPUT

      - name: Check if tag for docs-builder already exists
        id: docs-builder-tag-in-repositories
        shell: bash
        run: |
          if docker buildx imagetools inspect docker://${{ env.QUAY_ORGANIZATION_DEV }}/docs-builder:${{ steps.docs-builder-tag.outputs.tag }} &>/dev/null; then
            echo exists="true" >> $GITHUB_OUTPUT
          else
            echo exists="false" >> $GITHUB_OUTPUT
          fi

      - name: Login to DockerHub
        if: ${{ steps.docs-builder-tag-in-repositories.outputs.exists == 'false' }}
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build docs-builder image
        if: ${{ steps.docs-builder-tag-in-repositories.outputs.exists == 'false' }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        id: docker_build_docs_builder
        with:
          provenance: false
          context: ./Documentation
          file: ./Documentation/Dockerfile
          push: true
          tags: |
            docker://${{ env.QUAY_ORGANIZATION_DEV }}/docs-builder:${{ steps.docs-builder-tag.outputs.tag }}

      - name: Retrieve image digest
        if: ${{ steps.docs-builder-tag-in-repositories.outputs.exists == 'false' }}
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "## docs-builder" > image-digest/docs-builder.txt
          echo "" >> image-digest/docs-builder.txt
          echo "\`docker://${{ env.QUAY_ORGANIZATION_DEV }}/docs-builder:${{ steps.docs-builder-tag.outputs.tag }}@${{ steps.docker_build_docs_builder.outputs.digest }}\`" >> image-digest/docs-builder.txt
          echo "" >> image-digest/docs-builder.txt

      - name: Upload artifact digests
        if: ${{ steps.docs-builder-tag-in-repositories.outputs.exists == 'false' }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: image-digest docs-builder
          path: image-digest
          retention-days: 1

      - name: Update docs-builder image reference in CI workflow
        if: ${{ steps.docs-builder-tag-in-repositories.outputs.exists == 'false' }}
        run: |
          Documentation/update-docs-builder-image.sh "docker://${{ env.QUAY_ORGANIZATION_DEV }}/docs-builder:${{ steps.docs-builder-tag.outputs.tag }}@${{ steps.docker_build_docs_builder.outputs.digest }}"
          git commit -sam "ci: update docs-builder"

      - name: Get token
        if: ${{ steps.docs-builder-tag-in-repositories.outputs.exists == 'false' }}
        id: get_token
        uses: cilium/actions-app-token@350a14155dd9be79227f081310f4d77fdf792e76 # v0.21.0
        with:
          APP_PEM: ${{ secrets.AUTO_COMMITTER_PEM }}
          APP_ID: ${{ secrets.AUTO_COMMITTER_APP_ID }}

      - name: Push changes into PR
        if: ${{ steps.docs-builder-tag-in-repositories.outputs.exists == 'false' }}
        run: |
          git diff HEAD^
          git push https://x-access-token:${{ steps.get_token.outputs.app_token }}@github.com/${{ env.QUAY_ORGANIZATION }}/cilium.git HEAD:${{ github.event.pull_request.head.ref }}

  image-digests:
    name: Display digests
    runs-on: ubuntu-20.04
    needs: build-and-push
    steps:
      - name: Create image digest directory
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download image digest
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          path: image-digest/

      - name: Output image digest
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
